<<<<<<< HEAD
spring.application.name=productdb
server.port=2026

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2
=======
spring.application.name=demo1
server.port=9090
>>>>>>> 3b99ed717fe991ecd488292f6867b8eb21a62711
